language: go

go:
  - 1.6

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - go get github.com/GeertJohan/fgt
  - go get github.com/fzipp/gocyclo

script:
  - fgt go fmt ./...
  - fgt gocyclo -over 10 .
  - fgt go vet ./...
  - fgt golint ./...
  - go test -bench . -benchmem ./...
  - bin/coverage
